version: "3"

services:
  watchtower:
    container_name: watchtower
    restart: always

    environment:

      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: <FROM_EMAIL>
      WATCHTOWER_NOTIFICATION_EMAIL_TO: <TO_EMAIL>
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: <SERVER_EMAIL>
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: <USER_EMAIL>
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: <PASSWORD_EMAIL>
      WATCHTOWER_SCHEDULE: 0 0 4 * * *
      TZ: Europe/Paris
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_DEBUG: "true"

    image: containrrr/watchtower

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
